name: ForumSignin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  checkin:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync with upstream
        if: github.repository != 'LovesAsuna/ForumSignin'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          upstream_sync_repo: LovesAsuna/ForumSignin
          upstream_sync_branch: master
          target_sync_branch: master
          git_pull_args: '-s recursive -Xtheirs'

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Checkin
        env:
          ZDFX_COOKIE: ${{ secrets.ZDFX_COOKIE }}
          HUAHUO_COOKIE: ${{ secrets.HUAHUO_COOKIE }}
        run: ./gradlew run --no-daemon
