name: ForumSignin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Checkin
        env:
          ZDFX_COOKIE: ${{ secrets.ZDFX_COOKIE }}
          HUAHUO_COOKIE: ${{ secrets.HUAHUO_COOKIE }}
        run: ./gradlew run --no-daemon
