name: ForumSignin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync with upstream
        if: github.repository != 'LovesAsuna/ForumSignin'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
        with:
          upstream_repository: LovesAsuna/ForumSignin
          upstream_branch: master
          target_branch: master
          git_pull_args: '-s recursive -Xtheirs'

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0
        with:
          chrome-version: stable

      - name: download chrome ChromeDriver
        run: wget https://npm.taobao.org/mirrors/chromedriver/97.0.4692.71/chromedriver_linux64.zip

      - name: unzip ChromeDriver
        run: unzip chromedriver_linux64.zip

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Checkin
        env:
          ZDFX_COOKIE: ${{ secrets.ZDFX_COOKIE }}
          HUAHUO_COOKIE: ${{ secrets.HUAHUO_COOKIE }}
        run: ./gradlew run --no-daemon
